### ISSUE TITLE
Refactor Tracer object to take in multiple DataTransformer objects

### ISSUE THREAD

**Issue by itshady** [macformula/hil#47]
Suggested solution:
Create a DataTransformer interface which will have concrete implementations that take in data from the CAN Tracer object and then transform and manipulate that data (ex. an MCAP implementation of DataTransformer would take the data and write it to an MCAP file, whereas a CSV implementation would write to a csv).

Define the interface here. This interface will be needed for MCAP generation.

**Comment by samparent97** [comment]
closed with #67
